### ISSUE TITLE
Influx DB not working

### ISSUE THREAD

**Issue by Vikath** [fablab-ka/LasaurApp#5]
When i installed "root@lasersaur:/home/fabi/LasaurApp# pip install influxdb", folowwing error message appears when starting the LaserSaur "./run.sh":

root@lasersaur:/home/fabi/LasaurApp# ./run.sh 
loading config file /home/fabi/LasaurApp/backend/config.json
Traceback (most recent call last):
  File "backend/app.py", line 9, in <module>
    from serial_manager import SerialManager
  File "/home/fabi/LasaurApp/backend/serial_manager.py", line 506, in <module>
    SerialManager = SerialManagerClass()
  File "/home/fabi/LasaurApp/backend/serial_manager.py", line 61, in **init**
    self.reset_accounting()
  File "/home/fabi/LasaurApp/backend/serial_manager.py", line 132, in reset_accounting
    self.logger.info("Reset Accounting")
  File "/home/fabi/LasaurApp/backend/remotelogger.py", line 63, in info
    "message": message
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 391, in write_points
    tags=tags)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 436, in _write_points
    expected_response_code=204
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 276, in write
    data=make_lines(data, precision).encode('utf-8'),
  File "/usr/local/lib/python2.7/dist-packages/influxdb/line_protocol.py", line 117, in make_lines
    for field_key in sorted(point['fields'].keys()):
KeyError: u'fields'

**Comment by mostley** [comment]
seems like the influx db isn't set up properly or not available. The error message could be better though
